export const POKEMONS_FETCH_DATA_SUCCESS = "POKEMONS_FETCH_DATA_SUCCESS";
export const POKEMON_FETCH_DATA_SUCCESS = "POKEMON_FETCH_DATA_SUCCESS";
export const POKEMONS_LIST_FETCH_DATA_SUCCESS = "POKEMONS_LIST_FETCH_DATA_SUCCESS";
export const LIST_IS_OPEN_SUCCESS = "LIST_IS_OPEN_SUCCESS";
export const FETCH_IS_START = "FETCH_IS_START";
export const FETCH_ERROR = "FETCH_ERROR";
